name: CI - Feature Branches

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build e Testes de Unidade (.NET)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar o projeto
        run: dotnet build --no-restore --configuration Release

      - name: Executar testes de unidade
        run: dotnet test --no-build --verbosity normal --configuration Release