name: Create PR to development

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request to development
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update from feature branch"
          branch: ${{ github.ref_name }}
          base: development
          title: "Feature: ${{ github.ref_name }}"
          body: |
            PR automática criada a partir da branch `${{ github.ref_name }}` para `development`.
            Por favor, adicionar reviewers e aguardar CI.
          labels: automatic-pr
